- project:
    templates:
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-victoria-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - openstackclient-plugin-jobs
    gate:
      queue: qinling

