- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - check-requirements
      - openstackclient-plugin-jobs
    check:
      jobs:
        - openstack-tox-cover:
            voting: false
    gate:
      queue: qinling
